### ISSUE TITLE
Determine public transport stations and put them into database

### ISSUE THREAD

**Issue by wolfhardfehre** [wolfhardfehre/olli-simulation#19]

**Comment by derhuerst** [comment]
You may be interested in [`vbb-stations`](https://www.npmjs.com/package/vbb-stations).

**Comment by wolfhardfehre** [comment]
@derhuerst do you see a way of querying the next 3 arrivals at the 10 closest/nearby stations?

**Comment by derhuerst** [comment]
Yes.

You can query nearby stations at `https://vbb.transport.rest/stations/nearby?latitude=52.52725&longitude=13.4123`, or hard-code them.

You can query departures at `https://vbb.transport.rest/stations/900000100016/departures`.

Check the [full API docs](https://github.com/derhuerst/vbb-rest/blob/0589930aac08296877d8626193d5ea68aee03c95/docs/index.md).

**Comment by wolfhardfehre** [comment]
@derhuerst ok that is what I thought, I'll give it a try tomorrow ;) thx a lot!

**Comment by derhuerst** [comment]
I've shut the old API at `vbb.transport.rest` off now. Please use the new API at `2.vbb.transport.rest`, documented [here](https://github.com/derhuerst/vbb-rest/blob/2/docs/index.md).
